apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnoe-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/idp.git  # Update with your repo
    targetRevision: main
    path: infrastructure/kubernetes/cnoe-platform
  destination:
    server: https://kubernetes.default.svc
    namespace: cnoe-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
